server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo_app
    username: admin1
    password: root 
  jpa:
    generate-ddl: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
