


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cargo_app
    username: admin1
    password: root

  jpa:
    generate-ddl: false
  h2:
    console:
      enabled: true
      path: /h2-console
      
  cloud:
    stream:
      bindings:       
        cargoHandlingChannel:
          destination: cargoHandling
         
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
server:
  port: 8083